rate: 15
server_ip: "10.06.24.2"
table_name: "SmartDashboard"

# Wanted Output Data ("number", "string", "boolean")
output_data: [{name: "/cmd_vel/left", type: "number", default: 0.0},
              {name: "/cmd_vel/right", type: "number", default: 0.0}, 
              {name: "/turret/cmd_vel", type: "number", default: 0.0}, 
              {name: "/turret/distance", type: "number", default: 0.0}, 
              {name: "/auto/turret/state", type: "string", default: ""}, 
              {name: "/auto/intake/state", type: "string", default: ""}]

# Wanted Input Data ("number", "string", "boolean")
input_data: [{name: "/auto/state", type: "boolean", default: false}, 
             {name: "/auto/select", type: "number", default: 2}]